name: Build and Deploy Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Adding Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 21.5.0

    - name: Install deps
      working-directory: ./Milsymbol-Angular-Showcase
      run: npm install

    - name: run build
      working-directory: ./Milsymbol-Angular-Showcase
      run: npm run build

    # - name: deploy to gh-pages
    #   working-directory: ./Milsymbol-Angular-Showcase
    #   run: | 
    #     npx angular-cli-ghpages --dir=dist/milsymbol-angular-showcase
    #   env:
    #     CI: true
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: ./Milsymbol-Angular-Showcase/dist/milsymbol-angular-showcase # The folder the action should deploy.     
